First pass at also supporting pip installations (#1996)
* scripts: remove __init__.py (not a package)

* Travis: add environment for pip setup, refactor

- pip: download data
- refactor unit tests execution
- install pytest & pytest.cov
- don't source launcher
- remove MPLBACKEND envar
- no need to set PYTHONPATH for sct_testing
- run unit tests before integration tests

* add generic requirements.txt

* install_sct: update to piggy-back on pip install and more

- add anaconda-client
- don't install SCT from static requirements, use our setup.py
- run "sct_check_dependencies"
- add conda-forge source
- remove usage of update_bin script to create bins
- adjust paths without sct_env
- create launchers after install
- remove sentry DSN, write a sentry module

* add launcher for scripts

* sct_utils: add special case for SCT binaries (WIP)

* flag is_sct_binary in isct_* calls

* sct_utils: download binaries

* install: directly call scripts now they are reachable

* move the best parts of sct_utils into spinalcordtoolbox.utils

* launcher: force scripts to not use graphical output (#2005)

* documentation: sphinx: introduce the pip install

* setup: handle full install (except data & binaries) with pip

* launcher: handle MPI, ITK # threads

* sct_check_dependencies: fixup failing MPLBACKEND thing

* use __sct_dir__, __data_dir__

* sct_utils move logger

* documentation: sphinx: command-line: don't call python scripts as is, call the command

* unit_testing: deepseg_gm: fixup pytest.approx spec

* conda: explicit scipy installation

* requirements: simplify requirements (conda/pip), the specs are already constraining because of pyqt/sklearn

- dependencies versions are minimally fixated
- mpi option via setup

* is_sct_binary

* sct_check_dependencies: rework dependency checks

- Look at Conda requirements
- Look at pip requirements

* sct_utils: is_sct_binary

* install: remove obsolete update_bin, sct_env, sct_launcher

* documentation: sphinx: install: don't tell people to install without --user

* deepseg_gm: use __data_dir__

* launcher: just exec()

* sct_utils: add elapsed time counter (should not be here by default)

* sct_utils: elapsed fixup

* launcher: fixup

* sct_utils: counter fixup

* sct_utils: optional elapsed time counter

* Travis: WIP on #1898

* Travis: WIP gdb

* Travis: OSX gdb

* Travis: OSX to use lldb

* Travis: OSX with one job?

* Travis: OSX also multiproc

* Travis: OSX

* sct_check_dependencies: MPLBACKEND thing

* launcher style

* fixup rebasing -- lost is_sct_binary

* try out updating requirements

* sct_testing: format exceptions

* sct_testing: fixup encoding bug

* fixup ^

* scripts: sct_testing: simplify write_to_log_file

* unit_testing: image: remove fixtures

* unit_testing: image: fixups

* Travis: download sct_testing_data which is used by unit & integration tests

* centerline: nurbs: fixup use of linspace with non-int steps

* sct_utils: fixup missing string escapes

* image: fixup nibabel deprecation warning

* unit_testing: centerline: fixup linting error

* vertebrae: detect_c2c3: fixup is_sct_binary call

* install_sct: prepend SCT path, don't append

It's not a good idea to do that in principle, but users who install SCT
can install several versions without garbage-collecting their shrc.

* requirements: fixup portalocker addition

* sct_warp_template: fixup is_sct_binary

* straightening: fixup is_sct_binary

* sct_testing: catch sct.RunError

* resampling: fixup logging

* msct_register: fixup is_sct_binary


Former-commit-id: c469d44f3e07487578d4ac32abc61005ec1aa215

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,30 +19,32 @@ matrix:
   include:
 #    - os: linux
 #      python: 2.7 # Just to make travis's UI a bit prettier
-#      env: SCT_MINICONDA=2 SCT_VERBOSE_INSTALL=1 MPLBACKEND=Agg
+#      env: SCT_MINICONDA=2 SCT_VERBOSE_INSTALL=1
     - os: linux
       dist: xenial
       python: 2.7
-      env: SCT_MINICONDA=2 MPLBACKEND=Agg
+    - os: linux
+      python: 2.7
+      env: SCT_MINICONDA=2
 #    - os: linux
 #      python: 2.7
-#      env: SCT_MINICONDA=3 MPLBACKEND=Agg
+#      env: SCT_MINICONDA=3
     - os: osx
       language: generic
-      env: SCT_MINICONDA=2 MPLBACKEND=Agg
+      env: SCT_MINICONDA=2
 #    - os: osx
 #      language: generic
-#      env: SCT_MINICONDA=2 SCT_VERBOSE_INSTALL=1 MPLBACKEND=Agg
+#      env: SCT_MINICONDA=2 SCT_VERBOSE_INSTALL=1
 #    - os: osx
 #      language: generic
-#      env: SCT_MINICONDA=3 MPLBACKEND=Agg
+#      env: SCT_MINICONDA=3
   allow_failures:
     - os: linux
       python: 2.7
-      env: SCT_MINICONDA=3 MPLBACKEND=Agg
+      env: SCT_MINICONDA=3
     - os: osx
       language: generic
-      env: SCT_MINICONDA=3 MPLBACKEND=Agg
+      env: SCT_MINICONDA=3
 
 before_install:
   - echo "HOME="
@@ -53,26 +55,88 @@ before_install:
 install:
 # update tools
 #  - ./update_bin.sh
-  - yes | ASK_REPORT_QUESTION=false ./install_sct
-  # run launcher in order to update PATH
-  - source $HOME/build/neuropoly/spinalcordtoolbox/bin/sct_launcher
-  - echo $PATH
+  - |
+    echo Installing SCT
+    if [ "x${SCT_MINICONDA}" == "x" ]; then
+     pip install --upgrade pip
+     #pip install numpy
+     pip install -e .
+     mkdir data
+     cd data
+     for data in PAM50 gm_model optic_models pmj_models deepseg_sc_models deepseg_gm_models deepseg_lesion_models; do
+      sct_download_data -d ${data}
+     done
+     cd -
+    else
+     yes | ASK_REPORT_QUESTION=false ./install_sct
+     PATH="$PATH:$PWD/bin"
+    fi
 
 script:
 # test dependencies
 #  - sct_check_dependencies
 # test functions & integrity
 #  - bash -c "sudo apt-get install -qq libalglib-dev libinsighttoolkit4-dev; apt-cache show libvtk6-dev && sudo apt-get install -qq libvtk6-dev; apt-cache show libvtk7-dev && sudo apt-get install -qq libvtk7-dev; cd $HOME/build/neuropoly/spinalcordtoolbox/dev/isct_propseg; mkdir -p build; cd build; cmake ..; make; echo"
-  - pip install pylint
-  - bash -c "PYTHONPATH=\"$PWD/scripts:$PWD\" pylint -j3 --py3k --output-format=parseable --errors-only $(git ls-tree --name-only -r HEAD | sort | grep -E '(spinalcordtoolbox|scripts|testing).*\.py' | xargs); exit $(((($?&3))!=0))"
-  - pip install coverage
-  - bash -c 'echo -ne "import coverage\ncov = coverage.process_startup()\n" > sitecustomize.py'
-  - bash -c 'echo -ne "[run]\nconcurrency = multiprocessing\nparallel = True\n" > .coveragerc'
-  - COVERAGE_PROCESS_START="$PWD/.coveragerc" COVERAGE_FILE="$PWD/.coverage" PYTHONPATH="$PWD" sct_testing -d 1 --abort-on-failure
-  - coverage combine
-  - ./unit_testing.sh
-  - bash -c "pip install sphinx sphinxcontrib.programoutput sphinx_rtd_theme; cd $HOME/build/neuropoly/spinalcordtoolbox/documentation/sphinx; make html; echo"
+
+  - |
+    echo Checking
+    echo $PATH
+    if [ "x${SCT_MINICONDA}" == "x" ]; then
+      :
+    else
+      ls -lA bin
+    fi
+    sct_download_data -d sct_testing_data # for tests
+
+  - |
+    echo Linting
+    pip install pylint
+    bash -c 'PYTHONPATH="$PWD/scripts:$PWD" pylint -j3 --py3k --output-format=parseable --errors-only $(git ls-tree --name-only -r HEAD | sort | grep -E "(spinalcordtoolbox|scripts|testing).*\.py" | xargs); exit $(((($?&3))!=0))'
+
+  - |
+    echo Configuring coverage
+    pip install coverage
+    echo -ne "import coverage\ncov = coverage.process_startup()\n" > sitecustomize.py
+    echo -ne "[run]\nconcurrency = multiprocessing\nparallel = True\n" > .coveragerc
+
+  - |
+    echo Installing and running pytest
+    PATH_="$PATH"
+    PATH="$PWD/python/bin:$PATH"
+    pip install pytest pytest.cov
+    PYTHONPATH=scripts pytest -v --cov-append --cov=spinalcordtoolbox --cov=scripts unit_testing/*.py
+    PATH="${PATH_}"
+
+  - |
+    echo Running integration tests
+    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
+      COVERAGE_PROCESS_START="$PWD/.coveragerc" COVERAGE_FILE="$PWD/.coverage" sct_testing -j1 -d 0 --abort-on-failure
+      #brew update;
+      #brew install gdb;
+      #COVERAGE_PROCESS_START="$PWD/.coveragerc" COVERAGE_FILE="$PWD/.coverage" gdb --batch --ex "b __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__"  -ex r --ex "threads apply all bt" -ex "quit" --args python/bin/python  $(which sct_testing) -d 1 --abort-on-failure
+      #COVERAGE_PROCESS_START="$PWD/.coveragerc" COVERAGE_FILE="$PWD/.coverage" \
+      # lldb --batch \
+      #  -o "breakpoint set --name __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__" \
+      #  -o "process launch -- scripts/sct_testing.py -j1 -d 1 --abort-on-failure" \
+      #  -o "thread backtrace all" \
+      #  -o "quit" \
+      #  python/bin/python
+      coverage combine
+    else
+      COVERAGE_PROCESS_START="$PWD/.coveragerc" COVERAGE_FILE="$PWD/.coverage" sct_testing -d 0 --abort-on-failure
+      coverage combine
+    fi
+
+  - |
+    echo Building docs
+    pip install sphinx sphinxcontrib.programoutput sphinx_rtd_theme
+    cd documentation/sphinx
+    make html
+    cd -
+
+
   - pip install coveralls
+
 #  - python create_package.py -s ${TRAVIS_OS_NAME}  # test package creation
 #  - cd ../spinalcordtoolbox_v*
 #  - yes | ./install_sct  # test installation of package
