Replace miniconda with miniforge

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -562,27 +562,27 @@ unset PYTHONPATH
 export PYTHONNOUSERSITE=1
 
 # Remove old python folder
-print info "Installing conda..."
+print info "Installing miniforge..."
 run rm -rf "$SCT_DIR/$PYTHON_DIR"
 run mkdir -p "$SCT_DIR/$PYTHON_DIR"
 
-# Download miniconda
+# Download miniforge
 case $OS in
 linux*)
-  download "$TMP_DIR/"miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
+  download "$TMP_DIR/"miniforge.sh https://github.com/conda-forge/miniforge/releases/download/24.11.2-1/Miniforge3-Linux-x86_64.sh
   ;;
 osx)
-  download "$TMP_DIR/"miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
+  download "$TMP_DIR/"miniforge.sh https://github.com/conda-forge/miniforge/releases/download/24.11.2-1/Miniforge3-MacOSX-x86_64.sh
   ;;
 esac
 
 # Run conda installer
-run bash "$TMP_DIR/miniconda.sh" -p "$SCT_DIR/$PYTHON_DIR" -b -f
+run bash "$TMP_DIR/miniforge.sh" -p "$SCT_DIR/$PYTHON_DIR" -b -f
 
 # create py3.6 venv (for Keras/TF compatibility with Centos7, see issue #2270)
 python/bin/conda create -y -n venv_sct python=3.6 pip==21.2.2 setuptools==58.0.4 wheel==0.37.1 packaging==21.3
 
-# activate miniconda
+# activate miniforge
 # shellcheck disable=SC1091
 source python/etc/profile.d/conda.sh
 set +u #disable safeties, for conda is not written to their standard.
@@ -593,7 +593,7 @@ set -u # reactivate safeties
 EXPECTED_PYTHON="$(realpath "$(command -v python/envs/venv_sct/bin/python)")"
 ACTUAL_PYTHON="$(realpath "$(command -v python)")"
 if [ "$ACTUAL_PYTHON" != "$EXPECTED_PYTHON"  ]; then
-  echo "Error: Activating venv_sct failed to switch Python interpreter to Miniconda. (Incorrect interpreter loaded: $ACTUAL_PYTHON)" >&2
+  echo "Error: Activating venv_sct failed to switch Python interpreter to miniforge. (Incorrect interpreter loaded: $ACTUAL_PYTHON)" >&2
   exit 1
 fi
 
