Download function uses wget before using curl
Because outdated curl commands fail to download from the OSF site. The hack is
to use wget first, hoping that the system also has wget installed and is recent.


Former-commit-id: 33b90d64e49b557c9520a2ba8bc42f919584f900

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -100,36 +100,38 @@ install_refresh ()
 download ()
 {
   # Use curl or wget to download goodies
-  set -x
-  if hash "curl" ; then
-    curl -o $1 -L $2
-    e_status=$?
-    echo exit status is ${e_status}
+    e_status=0
 
-  elif hash "wget"; then
-    wget -O $1 $2
-    e_status=$?
-    echo exit status is ${e_status}
+    hash "wget" 2> /dev/null
+    is_wget=$?
+    hash "curl" 2> /dev/null
+    is_curl=$?
 
-  else
-    set +x
-    echo You need to install "curl" OR "wget" before you can install the SPINALCORDTOOLBOX
-    echo run
-    echo "   > sudo apt-get install wget"
-    echo and rerun the installer
-    exit 1
-  fi
-  set +x
+    if [[ ${is_wget} -eq 0 ]] ; then
+        wget -O $1 $2
+        e_status=$?
+        echo exit status is ${e_status}
+    fi
 
-  ls ${1}
-  file_exist=$?
+    if [[ ${is_curl} -eq 0 && ! -e $1 ]] ; then
+        curl -o $1 -L $2
+        e_status=$?
+        echo exit status is ${e_status}
+    fi
 
-  if [[ ${e_status} != 0  || ${file_exist} != 0 ]]; then
-     echo "The download of $2 failed"
-     echo "Please check your internet connection before relaunching the installer"
-     exit 1
-  fi
+    if [[ ! ${is_curl} && ! ${is_wget} ]] ; then
+        echo You need to install "curl" OR "wget" before you can install the SPINALCORDTOOLBOX
+        echo run
+        echo "   > sudo apt-get install wget"
+        echo and rerun the installer
+        exit 1
+    fi
 
+    if [[ ${e_status} -ne 0  || ! -e $1 ]]; then
+        echo "The download of $2 failed"
+        echo "Please check your internet connection before relaunching the installer"
+        exit 1
+    fi
 }
 
 
