Check that conda actually activated.
This glues over a rare glitch in conda (#3029, https://github.com/conda/conda/issues/10401)

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -527,6 +527,11 @@ yes | python/bin/conda create -n venv_sct python=3.6
 # activate miniconda
 source python/etc/profile.d/conda.sh
 conda activate venv_sct
+if [ "$(which python)" != "$(which python/envs/venv_sct/bin/python)" ]; then
+  echo "error: venv_sct failed to activate." >&2
+  exit 1
+fi
+
 
 # Install Python dependencies
 print info "Installing Python dependencies..."
