Check if the output is different to 0

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -454,8 +454,8 @@ conda activate venv_sct
 echo -e "\nInstalling Python dependencies..."
 pip install numpy
 pip install -r requirements.txt  # we do not include the requirements inside the setup.py because it is much faster to install all dependencies first (uses pre-compiled wheels)
-if [[ $? ]]; then
-  die "pip install failed"
+if [[ $? != 0 ]]; then
+  die "Failed running pip install -r requirements.txt: $?"
 fi
 
 if [[ $SCT_MPI_MODE ]] ; then
