install_sct: Fixed checking gcc

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -81,33 +81,37 @@ function fetch_os_type() {
 # Checks if the necessary tools for SCT are installed on the machine
 function check_requirements() {
 
+  echo "Checking requirements..."
+  # check curl
   if [[ ! $(which curl) && ! $(which wget) ]]; then
-    die "Install \"curl\" OR \"wget\" before you can install the SPINALCORDTOOLBOX"
+    die "ERROR: neither \"curl\" nor \"wget\" is installed. Please install either of them and restart SCT installation."
   fi
 
+  # check git
   if [[ ! $(which git) ]]; then
-    die "You need to install \"git\" before you can install the SPINALCORDTOOLBOX \n
+    die "ERROR: \"git\" is not installed. Please install it and restart SCT installation.\n
 for installation instructions check: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
 "
   fi
 
-  if [[ ! $(which gcc) ]]; then
+  # check gcc
+  gcc --version > /dev/null 2>&1  # run silently, then check output status
+  if [[ ! $? ]]; then
     if [[ $OS == "osx" ]]; then
-      echo -e "\nYou need to install gcc before you can use the SPINALCORDTOOLBOX."
-      read -p 'Do you want to install gcc now (accepting to install gcc will also install brew in case it is not installed already)? [y]es/[n]o: ' -r GCC_INSTALL
+      echo -e "\nWARNING: \"gcc\" is not installed."
+      read -p 'Do you want to install \"gcc\" now? (accepting to install gcc will also install \"brew\" in case it is not installed already)? [y]es/[n]o: ' -r GCC_INSTALL
       if [[ $GCC_INSTALL =~ [Yy](es)? ]]; then
         if [[ ! $(which brew) ]]; then
           yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
         fi
         yes | brew install gcc
       else
-        die "Install \"gcc\" before you can install the SPINALCORDTOOLBOX"
+        die "Please install \"gcc\" and restart SCT installation."
       fi
     else
-      die "Install \"gcc\" before you can install the SPINALCORDTOOLBOX"
+      die "Please install \"gcc\" and restart SCT installation."
     fi
   fi
-
 }
 
 # Gets the shell rc file path
