install_sct: Run brew install in sudo and add install check

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -92,12 +92,17 @@ function check_requirements() {
   if [[ $? ]]; then
     if [[ $OS == "osx" ]]; then
       echo -e "WARNING: \"gcc\" is not installed."
-      read -p 'Do you want to install "gcc" now? (accepting to install "gcc" will also install "brew" in case it is not installed already)? [y]es/[n]o: ' -r GCC_INSTALL
+      read -p 'Do you want to install it now? (accepting to install "gcc" will also install "brew" in case it is not installed already)? [y]es/[n]o: ' -r GCC_INSTALL
       if [[ $GCC_INSTALL =~ [Yy](es)? ]]; then
         if [[ ! $(which brew) ]]; then
           yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
         fi
-        yes | brew install gcc
+        yes | sudo brew install gcc
+        # check if gcc install ran properly
+        gcc --version > /dev/null 2>&1  # run silently, then check output status
+        if [[ $? ]]; then
+          die "ERROR: Installation of \"gcc\" failed. Please contact SCT team for assistance."
+        fi
       else
         die "Please install \"gcc\" and restart SCT installation."
       fi
