install_sct: Various changes to installation script
- Update PATH within install script to run sct_check_dependencies
- Removed SCT_MINICONDA=2 option, fixed requirements install
- Added SCT_DIR in .bashrc
- Source environment before running check_dependencies and made it compatible for CSHRC
- Fixed UPDATE_PATH declaration
- Now declaring MPLBACKEND on headless systems

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -22,7 +22,7 @@
 
 # N.B. to generate and compress binaries, go to binary folder and type: tar -czf sct_binaries.tar.gz isct_*
 
-#set -e  # v: verbose, e: exit if non-zero output is encountered. Note: using set -e will exit even when trying to remove
+#set -e  # v: verbose, e: exit if non-zero output is encountered. Using set -e will exit even when trying to remove
 # a folder that already exists, therefore, it should only be used for debugging mode.
 # TODO add some doc to the installer
 # TODO: remove python folder if not empty
@@ -48,12 +48,12 @@ finish ()
     # Get back to starting point
     cd ${SCT_SOURCE}
     if [ ${value} -eq 0 ]; then
-        echo "Installation finished successfully"
+        echo -e "Installation finished successfully\n"
     elif [ ${value} -eq 99 ]; then
         # Showing usage with -h
         echo ""
     else
-        echo "Installation failed"
+        echo -e "Installation failed\n"
     fi
     # clean tmp_dir
     rm -r ${TMP_DIR}
@@ -87,24 +87,27 @@ fi"
 }
 
 # Installation text to insert in .bashrc
-install_refresh ()
+edit_bashrc ()
 {
-
   if [[ -z ${THE_CSHRC} ]]  ; then
     echo
     echo "" >> ${THE_BASHRC}
     echo "# SPINALCORDTOOLBOX (installed on $(date +%Y-%m-%d\ %H:%M:%S))" >> ${THE_BASHRC}
-    echo "PATH=\"${SCT_DIR}/${BIN_DIR}:\${PATH}\"" >> ${THE_BASHRC}
+    echo ${DISPLAY_UPDATE_PATH} >> ${THE_BASHRC}
+    echo "export SCT_DIR=${SCT_DIR}" >> ${THE_BASHRC}
+    echo "export MPLBACKEND=Agg" >> ${THE_BASHRC}
     echo "" >> ${THE_BASHRC}
   else
     # (t)csh for good measure
+    echo
     echo "" >> ${THE_CSHRC}
-    echo "# SPINALCORDTOOLBOX" >> ${THE_CSHRC}
-    echo "setenv PATH \"${SCT_DIR}/${BIN_DIR}:\${PATH}\"" >> ${THE_CSHRC}
+    echo "# SPINALCORDTOOLBOX (installed on $(date +%Y-%m-%d\ %H:%M:%S))" >> ${THE_CSHRC}
+    echo ${DISPLAY_UPDATE_PATH} >> ${THE_CSHRC}
+    echo "setenv SCT_DIR ${SCT_DIR}" >> ${THE_CSHRC}
+    echo "setenv MPLBACKEND Agg" >> ${THE_CSHRC}
     echo "" >> ${THE_CSHRC}
   fi
 }
-
 
 # Download from URL using curl/wget
 download ()
@@ -144,7 +147,6 @@ download ()
     fi
 }
 
-
 # Usage of this script
 usage()
 {
@@ -172,9 +174,7 @@ for arg in "$@"; do
   esac
 done
 
-
-
-while getopts ":dmhbpz" opt; do
+while getopts ":dmhbpv" opt; do
   case $opt in
     d)
       echo " data directory will not be (re)-installed"
@@ -192,13 +192,9 @@ while getopts ":dmhbpz" opt; do
       echo " Multiprocessing using MPI activated"
       export SCT_MPI_MODE=yes
       ;;
-    k)
-      echo " SCT will be installed with Python 2.7"
-      SCT_MINICONDA=2
-      ;;
-    x)
+    v)
       echo " Full verbose!"
-      SCT_VERBOSE_INSTALL=yes
+      set -x
       ;;
     h)
       usage
@@ -210,12 +206,6 @@ while getopts ":dmhbpz" opt; do
       ;;
   esac
 done
-
-
-if [ "x${SCT_VERBOSE_INSTALL}" == "x1" ]; then
-  set -x
-fi
-
 
 # Catch SCT version
 if [ -e "version.txt" ]; then
@@ -238,11 +228,6 @@ if [ "x${SCT_INSTALL_TYPE}" == "x" ]; then
     SCT_INSTALL_TYPE="package"
   fi
 fi
-
-if [ "x${SCT_MINICONDA}" == "x" ]; then
-  SCT_MINICONDA=3
-fi
-
 
 # Fetch OS type
 if uname -a | grep -i  darwin > /dev/null 2>&1; then
@@ -275,10 +260,20 @@ else
   exit 1
 fi
 
-#echo -e "\nInstallation info:"
+# Define sh files
+if echo $(ps -o comm= $PPID) | grep csh ;then
+  THE_CSHRC=${HOME}/.cshrc
+  THE_RC=${THE_CSHRC}
+else
+  THE_BASHRC=${HOME}/.bashrc
+  THE_RC=${THE_BASHRC}
+fi
+
+# Display install info
 echo -e "\nSCT version ......... "$SCT_VERSION
 echo -e "Installation type ... "$SCT_INSTALL_TYPE
 echo -e "Operating system .... "$OS
+echo -e "Shell ............... "$THE_RC
 # Check if sudo
 if [[ $UID == 0 ]]; then
   echo -e "sudo mode ........... 1"
@@ -309,25 +304,16 @@ else
   echo "--> Crash reports will not be sent."
 fi
 
-# Define sh files
-if echo $(ps -o comm= $PPID) | grep csh ;then
-  THE_CSHRC=${HOME}/.cshrc
-  THE_RC=${THE_CSHRC}
-else
-  THE_BASHRC=${HOME}/.bashrc
-  THE_RC=${THE_BASHRC}
-fi
-
 # if installing from git folder, then becomes default installation folder
 if [[ "${SCT_INSTALL_TYPE}" == "in-place" ]]; then
-  INSTALL_DIR=$SCT_SOURCE
+  SCT_DIR=$SCT_SOURCE
 else
-  INSTALL_DIR="${HOME}/sct_${SCT_VERSION}"
+  SCT_DIR="${HOME}/sct_${SCT_VERSION}"
 fi
 
 # Set install dir
 while true; do
-  echo -e "\nSCT will be installed here: [${INSTALL_DIR}]"
+  echo -e "\nSCT will be installed here: [${SCT_DIR}]"
   while  [[ ! ${change_default_path} =~ ^([Yy](es)?|[Nn]o?)$ ]] ; do
     echo -n "Do you agree? [y]es/[n]o: "
     read change_default_path
@@ -351,33 +337,52 @@ while true; do
     echo Please pick a full path
     continue
   elif [ -d "${new_install}" ]; then
-    # directory exists --> update INSTALL_DIR and exit loop
+    # directory exists --> update SCT_DIR and exit loop
     echo -e "WARNING: Directory already exists. Files will be overwritten."
-    INSTALL_DIR=${new_install}
+    SCT_DIR=${new_install}
     break
   elif [ ! "${new_install}" ]; then
     # If no input, asking again, and again, and again
     continue
   else
-    INSTALL_DIR=${new_install}
+    SCT_DIR=${new_install}
     break
   fi
 done
 
 # Create directory
-mkdir -p ${INSTALL_DIR}
+mkdir -p ${SCT_DIR}
 # check if directory was created
-if [ -d "${INSTALL_DIR}" ]; then
+if [ -d "${SCT_DIR}" ]; then
   # check write permission
-  if [ ! -w "${INSTALL_DIR}" ]; then
-    echo "ERROR: ${INSTALL_DIR} exists but does not have write permission."
+  if [ ! -w "${SCT_DIR}" ]; then
+    echo "ERROR: ${SCT_DIR} exists but does not have write permission."
     exit 1
   fi
 else
-  echo "ERROR: ${INSTALL_DIR} cannot be created. Make sure you have write permission."
+  echo "ERROR: ${SCT_DIR} cannot be created. Make sure you have write permission."
   exit 1
 fi
-SCT_DIR=${INSTALL_DIR}
+
+# Update PATH variables based on Shell type
+if [[ -z ${THE_CSHRC} ]]  ; then
+  UPDATE_PATH="export PATH=${SCT_DIR}/${BIN_DIR}:${PATH}"
+  DISPLAY_UPDATE_PATH="export PATH=\"${SCT_DIR}/${BIN_DIR}:\${PATH}\""
+else
+  UPDATE_PATH="setenv PATH ${SCT_DIR}/${BIN_DIR}:${PATH}"
+  DISPLAY_UPDATE_PATH="setenv PATH \"${SCT_DIR}/${BIN_DIR}:\${PATH}\""
+fi
+
+# Update MPLBACKEND on headless system. See: https://github.com/neuropoly/spinalcordtoolbox/issues/2137
+if [[ -z ${MPLBACKEND} ]] ; then
+  # using bash
+  if [[ -z ${THE_CSHRC} ]]  ; then
+    export MPLBACKEND=Agg
+  # using (t)csh
+  else
+    setenv MPLBACKEND Agg
+  fi
+fi
 
 # Copy files to destination directory
 if [ "${SCT_DIR}" != "${SCT_SOURCE}" ]; then
@@ -404,7 +409,7 @@ if [ ! -f "version.txt" ]; then
   exit 1
 fi
 
-## INSTALL PYTHON
+## Install Python
 # We make sure that there is no conflict with local python install by unsetting PYTHONPATH
 # and forcing PYTHONNOUSERSITE
 unset PYTHONPATH
@@ -421,27 +426,14 @@ else
   cmd="mkdir -p ${SCT_DIR}/${PYTHON_DIR}"; echo ">> "$cmd; $cmd
   # downloading
 
-  if [ $SCT_MINICONDA == "2" ]; then
-    case $OS in
-      linux*)
-      download ${TMP_DIR}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda2-4.1.11-Linux-x86_64.sh
-      ;;
-      osx)
-      download ${TMP_DIR}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda2-4.1.11-MacOSX-x86_64.sh
-      ;;
-    esac
-  elif [ $SCT_MINICONDA == "3" ]; then
-    case $OS in
-      linux*)
-      download ${TMP_DIR}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
-      ;;
-      osx)
-      download ${TMP_DIR}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
-      ;;
-    esac
-  else
-      download ${TMP_DIR}/miniconda.sh "$SCT_MINICONDA"
-  fi
+  case $OS in
+    linux*)
+    download ${TMP_DIR}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
+    ;;
+    osx)
+    download ${TMP_DIR}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
+    ;;
+  esac
 
   # run conda installer
   cmd="bash ${TMP_DIR}/miniconda.sh -p ${SCT_DIR}/${PYTHON_DIR} -b -f"; echo ">> "$cmd; $cmd
@@ -461,38 +453,12 @@ else
 
   # Install Python dependencies
   echo -e "\nInstalling Python dependencies..."
-
-  if [ "$SCT_MINICONDA" == "3" ]; then
-    echo "Working around dipy setup.py issue on py3k by installing numpy"
-    conda install -fy numpy
-  fi
-
-  if [ "$SCT_MINICONDA" == "3" ]; then
-    specs=$(< ${SCT_SOURCE}/install/requirements/requirementsConda.txt)
-    e_status=0
-    for spec in $specs; do
-      conda install --yes "$spec" || e_status=1
-    done
-    e_status=0 # Temporary until everything in there has been fixed
-  else
-    conda install --yes --file ${SCT_SOURCE}/install/requirements/requirementsConda.txt
-    e_status=$?
-  fi
-  if [ ${e_status} != 0 ] ; then
-    echo "conda install error with exit status $e_status. Check logs for more details
-            and verify your internet connection before reinstalling"
-    exit $e_status
-  fi
+  pip install numpy  # need to install numpy first, otherwise nipy install within requirements.txt fails
+  pip install -r requirements.txt  # we do not include the requirements inside the setup.py because it is much faster to install all dependencies first (uses pre-compiled wheels)
 
   if [[ ${SCT_MPI_MODE} ]] ; then
     echo "Installing MPI libraries for HPC installation"
       conda install -c conda-forge --yes --file ${SCT_SOURCE}/install/requirements/requirementsMPI.txt
-  fi
-
-  # Workaround for #1549 (install pip 10 pre-release if not already here)
-  if python -c 'import pip; int(pip.__version__.split(".")[0]) >= 10' | grep -q False; then
-    echo "Retrieving a recent pip to make installation faster"
-    pip install https://github.com/pypa/pip/archive/72f219c410b0ce25f7da44be6172c1e3766bbe6b.zip
   fi
 
 fi
@@ -501,20 +467,11 @@ fi
 pip install -e ${SCT_DIR}
 e_status=$?
 if [ ${e_status} != 0 ]; then
-  echo "Failed to pip install sct, which is quite unexpected."
+  echo "Failed to pip install sct."
   exit ${e_status}
 fi
 
-python ${SCT_SOURCE}/install/install_dependencies_with_workarounds.py
-e_status=$?
-if [ ${e_status} != 0 ]; then
-  echo "Working around distribution issues failed."
-  echo "Feel free to open an issue after looking at https://github.com/neuropoly/spinalcordtoolbox/issues/1704"
-  exit $e_status
-fi
-
 ## Create launchers for Python scripts
-
 echo -e "\nCreating launchers for Python scripts..."
 mkdir -p ${SCT_DIR}/bin
 for file in ${SCT_DIR}/python/bin/*sct*; do
@@ -525,7 +482,6 @@ for file in ${SCT_DIR}/python/bin/*sct*; do
     exit $res
   fi
 done
-
 
 ## Install binaries
 if [ ${NO_SCT_BIN_INSTALL} ]; then
@@ -552,11 +508,9 @@ else
   fi
 fi
 
-
 echo -e "All requirements installed!"
 
-
-# INSTALL DATA
+## Install data
 if [ ${NO_DATA_INSTALL} ]; then
   echo "data/ will not be (re)-install"
 else
@@ -578,9 +532,13 @@ else
   done
 fi
 
-# Deactivating conda
+## Deactivating conda
 . ${SCT_DIR}/${PYTHON_DIR}/bin/deactivate > /dev/null 2>&1
 
+## Update PATH within this script (to launch sct_check_dependencies)
+${UPDATE_PATH}
+
+## Validate installation and update .bashrc
 # if sudo=0
 if [[ $UID != 0 ]]; then
   # update PATH environment
@@ -590,31 +548,31 @@ if [[ $UID != 0 ]]; then
   done
   echo ""
   if [[ ${add_to_path} =~ ^[Yy] ]]; then
-    install_refresh
+    edit_bashrc
   else
-     echo Not adding ${INSTALL_DIR} to \$PATH
-     echo You can always add it later or call SCT functions with full path ${SCT_DIR}/${BIN_DIR}/sct_function
+    echo Not adding ${SCT_DIR} to \$PATH
+    echo You can always add it later or call SCT functions with full path ${SCT_DIR}/${BIN_DIR}/sct_function
   fi
   # run sct_check_dependencies
-  echo -e "\nValidate installation..."
+  echo -e "Validate installation..."
   # We run the sct_check_dependencies in the TMP_DIR so the tmp.XXX output
   # it creates is cleaned properly
   if sct_check_dependencies; then
     if [[ ${add_to_path} =~ ^[Nn] ]]; then
       echo -e "To use SCT, please update your environment by running:\n"
-      echo -e "PATH+=\":${SCT_DIR}/${BIN_DIR}\""
+      echo -e ${DISPLAY_UPDATE_PATH}
     else
       echo -e "Open a new Terminal window to load environment variables, or run:\n source ${THE_RC}\n"
     fi
   else
-    echo -e "Installation validation NG!"
-    echo -e "Please copy the historic of this Terminal (starting with the command install_sct) and paste it in the SCT Help forum under a new ticket:"
-    echo -e "https://sourceforge.net/p/spinalcordtoolbox/discussion/help/\n"
+    echo -e "Installation validation Failed!"
+    echo -e "Please copy the historic of this Terminal (starting with the command install_sct) and paste it in the SCT Help forum (create a new discussion):"
+    echo -e "http://forum.spinalcordmri.org/c/sct\n"
     exit 1
   fi
+# if sudo=1
 else
-  # if sudo=1
-  echo -e "\nWARNING: sudo mode: Profile file was not edited. To complete installation, please add the following line to the appropriate file (e.g., .bashrc):"
-  echo -e "PATH+=\":${SCT_DIR}/${BIN_DIR}\""
+  echo -e "\nWARNING: sudo mode: Profile file was not edited. To complete installation, please add the following line to ${THE_RC}:"
+  echo -e ${DISPLAY_UPDATE_PATH}
   echo -e "Then, please open a new Terminal and run sct_check_dependencies to make sure SCT is properly installed.\n"
 fi
