Replace miniconda with miniforge

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -572,20 +572,20 @@ fi
 run rm -rf "$SCT_DIR/$PYTHON_DIR"
 run mkdir -p "$SCT_DIR/$PYTHON_DIR"
 
-# Download miniconda
-print info "Downloading Miniconda..."
+# Download miniforge
+print info "Downloading miniforge..."
 case $OS in
 linux*)
-  download "$TMP_DIR/"miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
+  download "$TMP_DIR/"miniforge.sh https://github.com/conda-forge/miniforge/releases/download/24.11.2-1/Miniforge3-Linux-x86_64.sh
   ;;
 osx)
-  download "$TMP_DIR/"miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
+  download "$TMP_DIR/"miniforge.sh https://github.com/conda-forge/miniforge/releases/download/24.11.2-1/Miniforge3-MacOSX-x86_64.sh
   ;;
 esac
 
 # Run conda installer
-print info "Installing Miniconda..."
-run bash "$TMP_DIR/miniconda.sh" -p "$SCT_DIR/$PYTHON_DIR" -b -f
+print info "Installing miniforge..."
+run bash "$TMP_DIR/miniforge.sh" -p "$SCT_DIR/$PYTHON_DIR" -b -f
 
 # Workaround for WSL "HTTP 000 Connection Failed" error
 # See: https://github.com/conda/conda/issues/9948#issuecomment-909989810
@@ -605,7 +605,7 @@ find "$SCT_DIR/$PYTHON_DIR" -type f -exec touch {} +
 # * Fix details: https://github.com/conda/conda/issues/7173#issuecomment-980496682
 echo "include-system-site-packages = false" > "$SCT_DIR/$PYTHON_DIR/envs/venv_sct/pyvenv.cfg"
 
-# activate miniconda
+# activate miniforge
 # shellcheck disable=SC1091
 source python/etc/profile.d/conda.sh
 set +u #disable safeties, for conda is not written to their standard.
@@ -617,7 +617,7 @@ print info "Validating that conda environment can be activated..."
 EXPECTED_PYTHON="$(realpath "$(command -v python/envs/venv_sct/bin/python)")"
 ACTUAL_PYTHON="$(realpath "$(command -v python)")"
 if [ "$ACTUAL_PYTHON" != "$EXPECTED_PYTHON"  ]; then
-  echo "Error: Activating venv_sct failed to switch Python interpreter to Miniconda. (Incorrect interpreter loaded: $ACTUAL_PYTHON)" >&2
+  echo "Error: Activating venv_sct failed to switch Python interpreter to miniforge. (Incorrect interpreter loaded: $ACTUAL_PYTHON)" >&2
   exit 1
 fi
 
