Improve the readability of the test suite (#3423)
Readability changes include:

* Change pytest options to make them less verbose
* Split `.ci.sh` into functions to view tests separately from install log
* Check dependencies separately from installation
* `install_sct`: Use silent/no-verbose output for curl/wget
* Disable progress bars for CI workflows

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -21,6 +21,7 @@
 #  -y   Install without interruption with 'yes' as default answer
 #  -d   Prevent the (re)-installation of the data/ directory
 #  -b   Prevent the (re)-installation of the SCT binaries files
+#  -c   Prevent checks from being run to validate the installation
 #  -v   Full verbose
 #
 #
@@ -51,6 +52,7 @@ SCT_INSTALL_TYPE=""
 NONINTERACTIVE=""
 NO_DATA_INSTALL=""
 NO_SCT_BIN_INSTALL=""
+NO_INSTALL_VALIDATION=""
 
 # ======================================================================================================================
 # FUNCTIONS
@@ -275,8 +277,8 @@ function edit_shellrc() {
 
 # Download from URL using curl/wget
 function download() {
-  ( (command -v wget >/dev/null) && run wget -O "$1" "$2" ) ||
-  ( (command -v curl >/dev/null) && run curl -o "$1" -L "$2" ) ||
+  ( (command -v wget >/dev/null) && run wget -nv -O "$1" "$2" ) ||
+  ( (command -v curl >/dev/null) && run curl -sS -o "$1" -L "$2" ) ||
   die "The download of $2 failed
 Please check that you have wget or curl installed, and
 your internet connection before relaunching the installer"
@@ -352,7 +354,7 @@ for arg in "$@"; do
   esac
 done
 
-while getopts ":iydbvh" opt; do
+while getopts ":iydbcvh" opt; do
   case $opt in
   i)
     SCT_INSTALL_TYPE="in-place"
@@ -368,6 +370,10 @@ while getopts ":iydbvh" opt; do
   b)
     echo " SCT binaries will not be (re)-installed "
     NO_SCT_BIN_INSTALL="yes"
+    ;;
+  c)
+    echo " no checks will be run (installation will not be validated)"
+    NO_INSTALL_VALIDATION="yes"
     ;;
   v)
     echo " Full verbose!"
@@ -711,18 +717,22 @@ else
 You can always add it later or call SCT functions with full path $SCT_DIR/$BIN_DIR/sct_xxx"
 fi
 
-# run sct_check_dependencies
-print info "Validate installation..."
-# We run the sct_check_dependencies in the TMP_DIR so the tmp.XXX output
-# it creates is cleaned properly
-if sct_check_dependencies; then
-  if [[ "$add_to_path" =~ ^[Nn] ]]; then
-    print info "To use SCT, please update your environment by running:
-$DISPLAY_UPDATE_PATH"
-  else
-    print info "Open a new Terminal window to load environment variables, or run:
-source $RC_FILE_PATH"
-  fi
+if [[ -n "$NO_INSTALL_VALIDATION" ]]; then
+    print warning "WARNING: no checks will be run (installation will not be validated)"
 else
-  die "Installation validation Failed!"
+  # run sct_check_dependencies
+  print info "Validate installation..."
+  # We run the sct_check_dependencies in the TMP_DIR so the tmp.XXX output
+  # it creates is cleaned properly
+  if sct_check_dependencies; then
+    if [[ "$add_to_path" =~ ^[Nn] ]]; then
+      print info "To use SCT, please update your environment by running:
+  $DISPLAY_UPDATE_PATH"
+    else
+      print info "Open a new Terminal window to load environment variables, or run:
+  source $RC_FILE_PATH"
+    fi
+  else
+    die "Installation validation Failed!"
+  fi
 fi
