Add CI workflow step to detect broken links in repository files (#4395)
## Description

This PR adds a CI workflow to check the repository for broken links. Then, this PR fixes each broken link so that the test passes.

## Linked Issues/PRs

Fixes #4393.

diff --git a/.github/workflows/check-code-quality.yml b/.github/workflows/check-code-quality.yml
--- a/.github/workflows/check-code-quality.yml
+++ b/.github/workflows/check-code-quality.yml
@@ -31,3 +31,21 @@ jobs:
       uses: ludeeus/action-shellcheck@master
       with:
         severity: style
+
+    - name: Check for broken links
+      run: | 
+        touch valid_urls.txt redirected_urls.txt invalid_urls.txt
+        find . -type f \( -name "*.txt" -o -name "*.md" -o -name "*.py" -o -name "*.rst" \) \( \! -name 'CHANGES.md' \) | 
+          xargs grep -Eo "\b(https?)://[-A-Za-z0-9+&@#/%?=~_|$!:,.;]*[A-Za-z0-9+&@#/%=~_|$]" | 
+          sed 's/:/;/' | 
+          xargs -n 1 -P 8 ./.github/workflows/check-url.sh
+
+    - name: Summarize broken link check
+      run: |
+        NUM_OK=$(wc -l valid_urls.txt | cut -d " " -f 1)
+        NUM_REDIRECT=$(wc -l redirected_urls.txt | cut -d " " -f 1)
+        NUM_BAD=$(wc -l invalid_urls.txt | cut -d " " -f 1)
+        cat invalid_urls.txt
+        echo -en "========== \033[0;32m$NUM_OK passed\033[0;0m, \033[0;33m$NUM_REDIRECT redirected\033[0;0m, \033[0;31m$NUM_BAD failed\033[0;0m ==========\n"
+        exit $NUM_BAD
+
